### ISSUE TITLE
Admin: New Collections

### ISSUE THREAD

**Issue by kane-mason** [thomas4019/expressa#95] opened 2020-08-14 19:59 UTC
Hi,

Was creating new collections from the `/admin` panel and ran into the following problems:

1. Unable to give to give properties a description using json schema editor
2. When changing type to `number` and setting a min and max, the the request fails with a validation error but the collection creation succeeds
3. When creating a property of type 'object', after completing one object and returning to 'Add another field' on the root, the object you just created gets cleared (particularly furstrating after having created a long object!!)
4. There is an error in the console when clicking 'Add another field' (might be related to point 3)
![image](https://user-images.githubusercontent.com/23186829/90285808-dc311c00-de74-11ea-870d-9cd0fdb5fa82.png)
5. After having created a collection with any storage type, and adding data to the collection, the `_id` property is not populated, should be by default right? When using postgres, the id column is also empty. This seems to work fine for users though
6. For new collections all the `own` permissions do not get auto added to the Admin role, should they?
7. New permissions are added with `true` and not `1` as with the default collections, this seems to be updated when the server is restarted

**Comment by thomas4019** [comment] 2020-08-16 07:06
Thanks for all the feedback. Note that some of these changes will actually need to be done in my other repo [json-schema-editor](https://github.com/thomas4019/json-schema-editor) which hasn't been maintained as much over the years. Creating tickets is fine here too.

2, 3, 4, and 7 are now fixed. Thanks for including helpful details :)

1. Do you have a suggestion for how to add the ability to set descriptions without making it more cluttered? I agree this would be good and am thinking it could be done with a button and then a modal or something with a few additional options? 
5. Hmm, I'm not able to reproduce this with the "file" storage type. Can you provide a bit more info?
6. When creating the collection did you check the "documentsHaveOwners" checkbox? If you go and edit the schema in the UI to add it then it should get added.

**Comment by kane-mason** [comment] 2020-08-17 09:47
Hi,

Ok can confirm that 2, 3, 4 and 7 are fixed, thank you for prompt response!

Folowing up on the rest:

1 . I was under the impression this used to exist in the previous version of expressa, if it didn't then this is not an issue but a feature request and less urgent. I agree it would be more intuitive so be able to include it in the schema editor. I like the idea of having a modal for 'additional info', but at the same time im not sure how much additional info we will need, seems like only description is missing, and maybe for now a text field like the string format is sufficient

7 . I can confirm this works as you say

5 . So once i create a new collection. I then head on over to the data menu and open that collection. Then click 'Add' as seen below

![image](https://user-images.githubusercontent.com/23186829/90381363-909d8e80-e07d-11ea-90aa-eea481cb815e.png)

As seen in this collection i already added a document and the `_id` is not auto populated. Anyway so i clicked add

![image](https://user-images.githubusercontent.com/23186829/90381232-5d5aff80-e07d-11ea-991e-f185e5e2ecfa.png)

I fill in all the fields but leave `_id` empty because this is a generated field?

This is th result when using file storage

![image](https://user-images.githubusercontent.com/23186829/90381605-e6723680-e07d-11ea-873e-bdc2af7ca1c5.png)

And when using postgres

![image](https://user-images.githubusercontent.com/23186829/90381852-436dec80-e07e-11ea-85b5-367d1c76523a.png)

Am i doing something wrong? I believe the id was generated in the previous expressa?

Also i think it would be a good idea to hide fields who's values are generated

**Comment by thomas4019** [comment] 2020-08-18 15:07
I think I may know what's going on here now. Making any change to the data structure using the "JSON" button causes the admin tool to send a `_id: ''` in the payload. Should be a simple fix in the admin tool to prevent that.
<img width="584" alt="Screen Shot 2020-08-18 at 9 04 28 AM" src="https://user-images.githubusercontent.com/406149/90530195-d4ea6680-e131-11ea-8e28-c085cf654617.png">

Hiding generated fields (on create) does seem like a good idea for most collections.

**Comment by kane-mason** [comment] 2020-08-18 16:14
Possibly, but i never clicked the json button. And even now checking again the same thing happens

![image](https://user-images.githubusercontent.com/23186829/90538242-94fda080-e17e-11ea-867b-17b6bf1a8eda.png)

Notice also meta information has empty strings but that populates correctly on db

**Comment by kane-mason** [comment] 2020-08-18 17:23
Ok def confirmed the problem is related to the empty string being sent by admin, check in the db create is `=== 'undefined'` which fails. Unsure of fix is to update the check, or prevent _id being sent from admin which i will leave to you

**Comment by thomas4019** [comment] 2020-08-19 05:33
PR to fix is here, https://github.com/thomas4019/expressa/pull/100

**Comment by kane-mason** [comment] 2020-08-30 19:06
All issues appear to be resolved

**Closed** 2020-08-30 19:11 UTC
