### ISSUE TITLE
lot of errors on current node lts 

### ISSUE THREAD

**Issue by HansHammel** [thomas4019/expressa#3] opened 2016-11-23 00:00 UTC
#node v6.9.1, npm 4.0.2, Windows 10 64 Pro

**starting**

> node app.js

Example app listening on port 3000!
error reading settings
Error: could not load data
    at C:\expressa\myapp\node_modules\jfs\lib\Store.js:209:15
    at ReadFileContext.callback (C:\expressa\myapp\node_modules\jfs\lib\Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
validators loaded.

**navigation to http://localhost:3000/admin**

my err handler
TypeError: Cannot read property 'get' of undefined
    at getById (C:\expressa\myapp\node_modules\expressa\index.js:249:27)
    at C:\expressa\myapp\node_modules\expressa\index.js:106:2
    at Layer.handle [as handle_request] (C:\expressa\myapp\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\expressa\myapp\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\expressa\myapp\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\expressa\myapp\node_modules\express\lib\router\layer.js:95:5)
    at C:\expressa\myapp\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\expressa\myapp\node_modules\express\lib\router\index.js:330:12)
    at next (C:\expressa\myapp\node_modules\express\lib\router\index.js:271:10)
    at addRolePermissionsMiddleware (C:\expressa\myapp\node_modules\expressa\role_permissions.js:8:11)

**selecting filebased gives**

updated settings collection storage
updated collection collection storage
updated role collection storage
error adding collection permissions
Error: could not load data
    at C:\expressa\myapp\node_modules\jfs\lib\Store.js:209:15
    at ReadFileContext.callback (C:\expressa\myapp\node_modules\jfs\lib\Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
updated users collection storage
error adding collection permissions
Error: could not load data
    at C:\expressa\myapp\node_modules\jfs\lib\Store.js:209:15
    at ReadFileContext.callback (C:\expressa\myapp\node_modules\jfs\lib\Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
updated post collection storage
adding collection permissions for settings
updated settings collection storage
adding collection permissions for collection
updated collection collection storage
adding collection permissions for role
updated role collection storage
adding collection permissions for users
updated users collection storage
adding collection permissions for post
updated post collection storage

**when selecting mongodb**

Example app listening on port 3000!
error reading settings
Error: could not load data
    at C:\expressa\myapp\node_modules\jfs\lib\Store.js:209:15
    at ReadFileContext.callback (C:\expressa\myapp\node_modules\jfs\lib\Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
validators loaded.
my err handler
TypeError: Cannot read property 'get' of undefined
    at getById (C:\expressa\myapp\node_modules\expressa\index.js:249:27)
    at C:\expressa\myapp\node_modules\expressa\index.js:106:2
    at Layer.handle [as handle_request] (C:\expressa\myapp\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\expressa\myapp\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\expressa\myapp\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\expressa\myapp\node_modules\express\lib\router\layer.js:95:5)
    at C:\expressa\myapp\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\expressa\myapp\node_modules\express\lib\router\index.js:330:12)
    at next (C:\expressa\myapp\node_modules\express\lib\router\index.js:271:10)
    at addRolePermissionsMiddleware (C:\expressa\myapp\node_modules\expressa\role_permissions.js:8:11)
updated settings collection storage
updated collection collection storage
updated role collection storage
error adding collection permissions
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at module.exports (C:\expressa\myapp\node_modules\mongodb\lib\url_parser.js:17:23)
    at connect (C:\expressa\myapp\node_modules\mongodb\lib\mongo_client.js:290:16)
    at Function.MongoClient.connect (C:\expressa\myapp\node_modules\mongodb\lib\mongo_client.js:114:3)
    at C:\expressa\myapp\node_modules\expressa\db\mongo.js:51:17
    at Object.get (C:\expressa\myapp\node_modules\expressa\db\mongo.js:50:11)
    at addCollectionPermissions (C:\expressa\myapp\node_modules\expressa\collection_permissions.js:51:23)
    at C:\expressa\myapp\node_modules\expressa\index.js:118:11
    at Array.map (native)
updated users collection storage
error adding collection permissions
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at module.exports (C:\expressa\myapp\node_modules\mongodb\lib\url_parser.js:17:23)
    at connect (C:\expressa\myapp\node_modules\mongodb\lib\mongo_client.js:290:16)
    at Function.MongoClient.connect (C:\expressa\myapp\node_modules\mongodb\lib\mongo_client.js:114:3)
    at C:\expressa\myapp\node_modules\expressa\db\mongo.js:51:17
    at Object.get (C:\expressa\myapp\node_modules\expressa\db\mongo.js:50:11)
    at addCollectionPermissions (C:\expressa\myapp\node_modules\expressa\collection_permissions.js:51:23)
    at C:\expressa\myapp\node_modules\expressa\index.js:118:11
    at Array.map (native)
updated post collection storage
C:\expressa\myapp\node_modules\mongodb\lib\mongo_client.js:237
          throw err
          ^

Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (C:\expressa\myapp\node_modules\bson\lib\bson\objectid.js:34:11)
    at C:\expressa\myapp\node_modules\expressa\db\mongo.js:52:40
    at connectCallback (C:\expressa\myapp\node_modules\mongodb\lib\mongo_client.js:315:5)
    at C:\expressa\myapp\node_modules\mongodb\lib\mongo_client.js:234:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

...

**Comment by coderofsalvation** [comment] 2017-03-13 18:41
I had the 'could not load data' too.
But after creating some collections using express-admin it dissappeared.
I guess expressa doesn't really work well without collections.

**Comment by coderofsalvation** [comment] 2017-03-14 18:41
hm looking further into it.
The first 'starting' error is expected/is innocent.
The second one I can reproduce.
It seems that the "use-strict" is causing some problems.
I'll try to figure out where the problem is and write a test.

@thomas4019 any ideas?

**Comment by HansHammel** [comment] 2017-03-14 20:38
👍

**Comment by coderofsalvation** [comment] 2017-03-14 22:11
I think I fixed a couple of them, since authorization wasn't working properly with the lastest masterbranch: https://github.com/thomas4019/expressa/pull/16
Hans, could you check again?

@thomas4019 I tried suppressing the error below (which is normal), however I was unsuccesful. The Store needs to be created with a non-existing file, but does not allow catching the error :dancing_women: 

```
Example app listening on port 3000!
error reading settings
Error: could not load data
at C:\expressa\myapp\node_modules\jfs\lib\Store.js:209:15
at ReadFileContext.callback (C:\expressa\myapp\node_modules\jfs\lib\Store.js:94:16)
at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
validators loaded.
```

I've submitted https://github.com/flosse/json-file-store/pull/17 to the jsf-repo, so lets catch that error when it gets accepted :man_dancing:

**Comment by thomas4019** [comment] 2017-03-15 07:11
I fixed the the "TypeError: Cannot read property 'get' of undefined" by removing a ajax call in the latest version of expressa-admin. I haven't looked into the mongo errors yet.

**Comment by thomas4019** [comment] 2017-09-25 07:34
I just tested with Mongo and it seems to be working correctly. I'm going to close this issue since I think it's now obsolete.

**Closed by thomas4019** 2017-09-25 07:34 UTC
